# Generated by Django 5.1.3 on 2024-11-15 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='sub_category',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.link'),
        ),
    ]
