# Generated by Django 5.1.3 on 2024-11-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_page_sub_category_link_alter_page_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
