# Generated by Django 5.1.3 on 2024-11-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_link_link_category_slug_link_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=1, upload_to='images/news'),
            preserve_default=False,
        ),
    ]
