# Generated by Django 5.1.3 on 2024-11-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_page_description_page_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='uuid',
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
